### ISSUE TITLE
Feedback - Some keyboard support?

### ISSUE THREAD

**Issue by pksjce** [nitin42/react-color-tools#1]
I couldn't get tabbing to work on the color-picker. Also arrow keys on the rgb values would be really sweet.
![upanddown](https://user-images.githubusercontent.com/417268/46409491-1f8ab180-c759-11e8-9a47-b3dc721a383f.gif)

**Comment by nitin42** [comment]
Oh! You can navigate the picker through the keyboard. I don't see any problem with that.

About arrow keys, hm... it sounds interesting!
